--liquibase formatted sql

--changeset tschf:create_table_screen_ranking endDelimiter:; rollbackEndDelimiter:;
create table screen_ranking(
  screen_ranking_id number generated by default on null as identity primary key,
  country_id number not null references "COUNTRY" ("COUNTRY_ID"),
  week date not null check (week = trunc(week)) check (to_char(week, 'DY') = 'SUN'),
  category varchar2(5) not null check (category in ('Films', 'TV')),
  weekly_rank number not null check (weekly_rank between 1 and 10),
  show_title varchar2(512) not null,
  season_title varchar2(512) not null,
  cumulative_weeks_in_top_10 number not null,
  constraint screen_ranking_uk1 unique (country_id, week, category, weekly_rank)
);
--rollback drop table screen_ranking;

--changeset tschf:comments_screen_ranking runOnChange:true endDelimiter:; rollbackEndDelimiter:;
comment on table screen_ranking is 'Representation of the feed file of weekly rankings as downloaded from TODO';

comment on column screen_ranking.week is 'Per the netflix specification, the date the data is released is always on a Sunday';
--rollback not required
