--liquibase formatted sql

--changeset tschf:create_table_screen_ranking endDelimiter:; rollbackEndDelimiter:;
create table screen_ranking(
  screen_ranking_id number generated by default on null as identity primary key,
  country_name varchar2(128) not null,
  country_iso2 varchar2(2) not null,
  week date not null check (week = trunc(week)),
  category varchar2(5) not null check (category in ('Films', 'TV')),
  weekly_rank number not null check (weekly_rank between 1 and 10),
  show_title varchar2(512) not null,
  season_title varchar2(512) not null,
  cumulative_weeks_in_top_10 number not null,
  constraint screen_ranking_uk1 unique (country_iso2, week, category, weekly_rank)
);
--rollback drop table screen_ranking;
