--liquibase formatted sql

--changeset tschf:create_table_app_config endDelimiter:; rollbackEndDelimiter:;
create table app_config(
  app_config_id number generated by default on null as identity primary key,
  app_config_name varchar2(128) not null unique,
  app_config_value varchar2(4000) not null
);
--rollback drop table country;

--changeset tschf:comments_app_config runOnChange:true endDelimiter:; rollbackEndDelimiter:;
comment on table app_config is 'Store configuration data. Primarily a place to put TMDB API Key';
--rollback not required
