--liquibase formatted sql

--changeset tschf:create_table_country endDelimiter:; rollbackEndDelimiter:;
create table country(
  country_id number generated by default on null as identity primary key,
  country_name varchar2(128) not null,
  country_iso2 varchar2(2) not null unique
);
--rollback drop table country;

--changeset tschf:comments_country runOnChange:true endDelimiter:; rollbackEndDelimiter:;
comment on table country is 'Each country that Netflix supports';
--rollback not required
